spring.application.name=cliente
server.port=8082

# URL de conexión a H2 en memoria
spring.datasource.url=jdbc:h2:mem:cliente
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialecto de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Crear y actualizar tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
